language: java
jdk: oraclejdk8
sudo: false
dist: trusty
install: true
script:
- mvn clean package  sonar:sonar     -Dsonar.host.url=https://sonarcloud.io     -Dsonar.organization=raouf25-github     -Dsonar.login=d9bba4e85b51f2d3e224215005455b88d62f3e18
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
before_install:
- chmod +x mvnw
notifications:
  email:
    recipients:
    - makhlouf.raouf+travis@gmail.com
    - jarraymohamed92@hotmail.fr
    on_failure: always